### ISSUE TITLE
brew formula not working on x86 MacOS

### ISSUE THREAD

**Issue by nestoralonso** [ikebastuz/wiper#10]
Pretty nice app, after installed in MacOS x86 and executing it prints `Bad CPU type in executable` and exits:

==> Fetching ikebastuz/wiper/wiper
==> Downloading https://github.com/ikebastuz/wiper/releases/download/v0.2.0/wiper.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/797991587/3da5b64f-ff0d-49b7-9042-ac144e94e7aa?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=r
############################################################################################################################################################################################# 100.0%
==> Installing wiper from ikebastuz/wiper

🍺  /usr/local/Cellar/wiper/0.2.0: 4 files, 1.5MB, built in 1 second
==> Running `brew cleanup wiper`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /Users/foo/Library/Caches/Homebrew/wiper--0.1.1.tar.gz... (480.1KB)
☸️  main on 🅰 us-west-2
@…/baz ➜ wiper
-bash: /usr/local/bin/wiper: Bad CPU type in executable

**Comment by ikebastuz** [comment]
Thank you for raising it!

I'm not very familiar with homebrew flows. Updated the config to switch between arm & x86_64
Checked by installing on my old mac - it worked

The only thing - I still not sure how to properly re-install brew taps. Currently I'm doing it by
```bash
brew uninstall wiper
brew untap ikebastuz/wiper
brew tap ikebastuz/wiper
brew install wiper
```

So it kinda re-pulls fresh formulas. But feels wrong

Anyways - can you try it now?

**Comment by nestoralonso** [comment]
Still getting the same error, I tried with this 2 commands:
```
brew install wiper # with normal formulas this command also updates
brew reinstall wiper 
# it installed the 0.20 version
```

**Comment by nestoralonso** [comment]
But following your steps it does work, many thanks
