### ISSUE TITLE
Folder 'icons' look wrong

### ISSUE THREAD

**Issue by Jajcus** [ikebastuz/wiper#7]
Unicode placeholder characters are displayed instead of 'folder icons' when I run wiper in my Linux Mint.

I have tried different terminal apps and different fonts – nothing helps. Even some ASCII character would look better than that.

![image](https://github.com/ikebastuz/wiper/assets/765347/4a8a59e2-bcb8-4482-9512-46c443e109f1)
![image](https://github.com/ikebastuz/wiper/assets/765347/0f76b40e-6bfe-4812-ad28-d32f44c68525)
![image](https://github.com/ikebastuz/wiper/assets/765347/da940c3a-53cd-49e6-a34e-1da92a715ded)

**Comment by ikebastuz** [comment]
Oh, thank you for reporting it!
That is sad :(
It looked good to me probably because I have some Nerd Fonts installed

Simplified it a bit at #8
